plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.95'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.ALL
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

version = mod_version
group = mod_group_id

base {
    archivesName = 'mining_little_maid'
}

repositories {
    mavenCentral()
    flatDir {
        dir "libs"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
        }
        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
        }
        configureEach {
            jvmArguments = [
                    '-XX:+IgnoreUnrecognizedVMOptions',
                    '-XX:+AllowEnhancedClassRedefinition'
            ]
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // TouhouLittleMaid 主体模组，从 libs 目录加载
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:-removal']
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

java {
    withSourcesJar()
}
